##### Resampling.pptx

In [102]:
import pandas as pd
#Loading Dataset in DataFrame
houseprices = pd.DataFrame.from_csv('C://Users//Jayant//Desktop//sem2//DMPA//PythonSlides//HousePrices (1).csv', index_col=None)
houseprices

HomeID   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0         1  114300  1790         2          2       2    No         East
1         2  114200  2030         4          2       3    No         East
2         3  114800  1740         3          2       1    No         East
3         4   94700  1980         3          2       3    No         East
4         5  119800  2130         3          3       3    No         East
5         6  114600  1780         3          2       2    No        North
6         7  151600  1830         3          3       3   Yes         West
7         8  150700  2160         4          2       2    No         West
8         9  119200  2110         4          2       3    No         East
9        10  104000  1730         3          3       3    No         East
10       11  132500  2030         3          2       3   Yes         East
11       12  123000  1870         2          2       2   Yes         East
12       13  102600  1910         3          2       4    No        North
13       14  126300  2150         3          3       5   Yes        North
14       15  176800  2590         4          3       4    No         West
15       16  145800  1780         4          2       1    No         West
16       17  147100  2190         3          3       4   Yes         East
17       18   83600  1990         3          3       4    No        North
18       19  111400  1700         2          2       1   Yes         East
19       20  167200  1920         3          3       2   Yes         West
20       21  116200  1790         3          2       3    No         East
21       22  113800  2000         3          2       4    No        North
22       23   91700  1690         3          2       3    No        North
23       24  106100  1820         3          2       3   Yes        North
24       25  156400  2210         4          3       2   Yes         East
25       26  149300  2290         4          3       3    No        North
26       27  137000  2000         4          2       3    No         West
27       28   99300  1700         3          2       2    No         East
28       29   69100  1600         2          2       3    No        North
29       30  188000  2040         4          3       1   Yes         West
..      ...     ...   ...       ...        ...     ...   ...          ...
98       99  145500  2060         3          2       1    No         West
99      100  171000  2080         3          3       2   Yes         West
100     101  103200  2010         3          2       5    No        North
101     102  123100  2260         3          3       5    No         East
102     103  136800  2410         3          3       4    No         East
103     104  211200  2440         4          3       3   Yes         West
104     105   82300  1910         3          2       4    No         East
105     106  146900  2530         4          3       4    No         West
106     107  108500  2130         3          2       4    No        North
107     108  134000  1890         3          2       1   Yes         East
108     109  117000  1990         3          3       3   Yes         East
109     110  108700  2110         3          2       3    No         East
110     111  111600  1710         2          2       1    No        North
111     112  114900  1740         2          2       2    No        North
112     113  123600  1940         2          2       2   Yes         East
113     114  115700  2000         3          2       3   Yes        North
114     115  124500  2010         4          3       2    No         East
115     116  102500  1900         3          3       3    No        North
116     117  199500  2290         5          4       1   Yes         West
117     118  117800  1920         3          2       2    No        North
118     119  150200  1950         3          2       3   Yes        North
119     120  109700  1920         2          2       4    No        North
120     1

#### Cross Validation on the Linear Regression Model

In [103]:
#Simple Linear Regression

#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt

#Creating X and y variables for the linear regression
X = houseprices.iloc[:, 2:].values
y = houseprices.iloc[:, 1].values

#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 4] = labelencoder.fit_transform(X[:, 4])
X[:, 5] = labelencoder.fit_transform(X[:, 5])
onehotencoder = OneHotEncoder(categorical_features = [5], )
X = onehotencoder.fit_transform(X).toarray()

#Fitting simple linear regression to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

##### k-fold cross validation

In [104]:
# Applying k (10) -fold cross validation | scoring='neg_mean_squared_error'
from sklearn.model_selection import cross_val_score
mse = cross_val_score(regressor, X, y, scoring='neg_mean_squared_error', cv=10)

In [105]:
#mean squared error for 10 (k) fold cross validation
mse

array([ -3.70499454e+07,  -1.55331758e+08,  -1.14063097e+08,
        -8.41891380e+07,  -6.96237460e+07,  -1.64567385e+08,
        -2.21082935e+07,  -1.79642858e+08,  -1.51985102e+08,
        -1.17368112e+08])

In [106]:
#The mean mse and the 95% confidence interval of the mse estimate:
print("Mean Squared Error: %0.2f (+/- %0.2f)" % (mse.mean(), mse.std() * 2))

Mean Squared Error: -109592943.54 (+/- 104034014.00)


#### 'scoring' techniques other than 'neg_mean_squared_error' that can be used on regressors while cross validation: ‘neg_mean_absolute_error’, ‘neg_median_absolute_error’, ‘r2’. An example of r2 scoring:

In [107]:
# Applying k (10) -fold cross validation | scoring='r2'
from sklearn.model_selection import cross_val_score
r2 = cross_val_score(regressor, X, y, scoring='r2', cv=10)

In [108]:
#r2 for 10 (k) fold cross validation
r2

array([ 0.85945164,  0.80181341,  0.87602094,  0.84933797,  0.88992619,
        0.75043742,  0.97640115,  0.74289177,  0.36178479,  0.82455356])

In [109]:
#The mean r2 and the 95% confidence interval of the r2 estimate:
print("R2: %0.2f (+/- %0.2f)" % (r2.mean(), r2.std() * 2))

R2: 0.79 (+/- 0.32)


##### Leave One Out Cross Validation (nothing but K-Fold with k = number of samples)

In [110]:
# Applying Leave One Out (k = n) cross validation | scoring='neg_mean_squared_error'
from sklearn.model_selection import cross_val_score
mse = cross_val_score(regressor, X, y, scoring='neg_mean_squared_error', cv=len(X))

In [111]:
#mean squared error for Leave One Out cross validation
mse

array([ -1.37011082e+08,  -4.26140402e+06,  -3.47493442e+06,
        -2.28220286e+08,  -3.02196747e+07,  -4.11713871e+07,
        -1.03263184e+07,  -9.07362260e+06,  -1.56544406e+06,
        -2.18258878e+04,  -1.22658134e+07,  -3.30683115e+06,
        -1.54881041e+07,  -5.54902699e+06,  -1.00981676e+08,
        -2.00724563e+07,  -1.09013937e+08,  -8.26423049e+08,
        -1.80364215e+08,  -3.36483050e+07,  -3.22805512e+08,
        -1.12549385e+08,  -1.51716723e+07,  -2.07744231e+08,
        -8.69641014e+06,  -1.20072298e+08,  -5.60188735e+04,
        -1.25920800e+07,  -3.34163210e+08,  -6.20472697e+07,
        -5.10584143e+07,  -3.39697789e+08,  -2.08204592e+08,
        -1.56129230e+08,  -1.13256322e+08,  -5.21614826e+07,
        -6.94097174e+07,  -1.55901059e+08,  -9.70066844e+06,
        -3.78990199e+06,  -6.29819692e+07,  -1.36465514e+08,
        -8.33627430e+03,  -2.27590490e+08,  -1.53814740e+07,
        -9.80884459e+06,  -5.11758616e+07,  -4.58858393e+05,
        -7.81901774e+06,

In [112]:
#The mean mse and the 95% confidence interval of the mse estimate:
print("Mean Squared Error: %0.2f (+/- %0.2f)" % (mse.mean(), mse.std() * 2))

Mean Squared Error: -106351663.30 (+/- 329462451.22)


#### Cross Validation on the Logistic Regression model

In [165]:
#Loading Dataset in DataFrame
beerPref = pd.DataFrame.from_csv('C://Users//Jayant//Desktop//sem2//DMPA//PythonSlides//Beer+Preferences.csv', index_col=None)
beerPref

Gender  Married    Inc  Income  Age Preference
0        0        0  31779      32   46    Regular
1        1        1  32739      33   50    Regular
2        1        1  24302      24   46    Regular
3        1        1  64709      65   70    Regular
4        1        1  41882      42   54    Regular
5        1        0  38990      39   36    Regular
6        1        0  22408      22   40    Regular
7        1        1  25440      25   51    Regular
8        0        1  30784      31   52    Regular
9        1        0  31916      32   43    Regular
10       1        0  23234      23   31    Regular
11       0        1  51094      51   46    Regular
12       1        0  38176      38   40    Regular
13       1        0  28513      29   34    Regular
14       0        1  44955      45   53    Regular
15       0        1  42051      42   58    Regular
16       1        1  40955      41   69    Regular
17       0        1  36451      36   44    Regular
18       1        0  20945      21   42    Regular
19       0        1  33880      34   48    Regular
20       1        1  47667      48   87    Regular
21       1        0  29293      29   43    Regular
22       1        1  30081      30   56    Regular
23       0        1  37263      37   49    Regular
24       1        1  40582      41   66    Regular
25       1        0  29077      29   39    Regular
26       0        1  27280      27   55    Regular
27       0        0  28094      28   39    Regular
28       1        0  29728      30   41    Regular
29       1        0  49811      50   49    Regular
..     ...      ...    ...     ...  ...        ...
70       1        1  48957      49   33      Light
71       1        0  46626      47   46      Light
72       1        1  40261      40   31      Light
73       1        0  42775      43   27      Light
74       1        1  51578      52   45      Light
75       0        1  45610      46   38      Light
76       1        1  58164      58   30      Light
77       0        0  30841      31   24      Light
78       1        0  52341      52   42      Light
79       0        0  41779      42   39      Light
80       1        1  42404      42   30      Light
81       0        1  33700      34   25      Light
82       1        1  55281      55   48      Light
83       1        0  53768      54   34      Light
84       1        1  47797      48   49      Light
85       1        1  63555      64   62      Light
86       1        1  42108      42   26      Light
87       0        1  52875      53   71      Light
88       0        1  59485      59   36      Light
89       1        1  50517      51   38      Light
90       0        0  43593      44   27      Light
91       0        0  35406      35   29      Light
92       0        1  46273      46   56      Light
93       0        0  33088      33   22      Light
94       0        0  41391      41   54      Light
95       0        1  45133      45   51      Light
96       0        1  39942      40   21      Light
97       1        1  47495      47   35      Light
98       1        1  70981      71   45      Light
99       0        1  48259      48   32      Light

[100 rows x 6 columns]

In [178]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt

#Creating X and y variables for the linear regression
X = beerPref.iloc[:, [0,1,2,4]].values
y = beerPref.iloc[:, 5].values

#Fitting logistic regression to the training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

##### K-Fold Cross Validation

In [179]:
# Applying k (10) -fold cross validation | scoring='accuracy'
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X, y, scoring='accuracy', cv=10)

In [180]:
#accuracies for 10 (k) fold cross validation
accuracies

array([ 0.8,  0.9,  0.7,  0.9,  1. ,  0.9,  1. ,  0.9,  0.8,  0.8])

In [181]:
#The mean accracy and the 95% confidence interval of the accuracy estimate:
print("Accuracy: %0.2f (+/- %0.2f)" % (accuracies.mean(), accuracies.std() * 2))

Accuracy: 0.87 (+/- 0.18)


In [182]:
#Mean Error
#Mean Error
print("Error: %0.2f" % (1-accuracies.mean()))

Error: 0.13


#### 'scoring' techniques other than 'accuracy' that can be used on classifiers while cross validation: ‘average_precision’, ‘f1’, ‘neg_log_loss’, ‘precision’, ‘recall’, ‘roc_auc’.

##### Leave One Out Cross Validation (nothing but K-Fold with k = number of samples)

In [170]:
# Applying LOO cross validation | scoring='accuracy'
from sklearn import cross_validation
loo = cross_validation.LeaveOneOut(len(y))

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X, y, scoring='accuracy', cv=loo)

In [171]:
#accuracies for Leave One Out cross validation
accuracies

array([ 1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.])

In [176]:
#The mean accracy
print("Accuracy: %0.2f" % (accuracies.mean()))

Accuracy: 0.87


In [177]:
#Mean Error
print("Error: %0.2f" % (1-accuracies.mean()))

Error: 0.13
