#### Neural Networks 1

##### Multinomial Logistic Regression

In [1]:
import pandas as pd
#Loading Dataset in DataFrame
housePrices = pd.DataFrame.from_csv("C:\\Users\\Jayant\\Desktop\\DMPA\\PythonSlides\\HousePrices (1).csv", index_col=None)
housePrices

HomeID   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0         1  114300  1790         2          2       2    No         East
1         2  114200  2030         4          2       3    No         East
2         3  114800  1740         3          2       1    No         East
3         4   94700  1980         3          2       3    No         East
4         5  119800  2130         3          3       3    No         East
5         6  114600  1780         3          2       2    No        North
6         7  151600  1830         3          3       3   Yes         West
7         8  150700  2160         4          2       2    No         West
8         9  119200  2110         4          2       3    No         East
9        10  104000  1730         3          3       3    No         East
10       11  132500  2030         3          2       3   Yes         East
11       12  123000  1870         2          2       2   Yes         East
12       13  102600  1910         3          2       4    No        North
13       14  126300  2150         3          3       5   Yes        North
14       15  176800  2590         4          3       4    No         West
15       16  145800  1780         4          2       1    No         West
16       17  147100  2190         3          3       4   Yes         East
17       18   83600  1990         3          3       4    No        North
18       19  111400  1700         2          2       1   Yes         East
19       20  167200  1920         3          3       2   Yes         West
20       21  116200  1790         3          2       3    No         East
21       22  113800  2000         3          2       4    No        North
22       23   91700  1690         3          2       3    No        North
23       24  106100  1820         3          2       3   Yes        North
24       25  156400  2210         4          3       2   Yes         East
25       26  149300  2290         4          3       3    No        North
26       27  137000  2000         4          2       3    No         West
27       28   99300  1700         3          2       2    No         East
28       29   69100  1600         2          2       3    No        North
29       30  188000  2040         4          3       1   Yes         West
..      ...     ...   ...       ...        ...     ...   ...          ...
98       99  145500  2060         3          2       1    No         West
99      100  171000  2080         3          3       2   Yes         West
100     101  103200  2010         3          2       5    No        North
101     102  123100  2260         3          3       5    No         East
102     103  136800  2410         3          3       4    No         East
103     104  211200  2440         4          3       3   Yes         West
104     105   82300  1910         3          2       4    No         East
105     106  146900  2530         4          3       4    No         West
106     107  108500  2130         3          2       4    No        North
107     108  134000  1890         3          2       1   Yes         East
108     109  117000  1990         3          3       3   Yes         East
109     110  108700  2110         3          2       3    No         East
110     111  111600  1710         2          2       1    No        North
111     112  114900  1740         2          2       2    No        North
112     113  123600  1940         2          2       2   Yes         East
113     114  115700  2000         3          2       3   Yes        North
114     115  124500  2010         4          3       2    No         East
115     116  102500  1900         3          3       3    No        North
116     117  199500  2290         5          4       1   Yes         West
117     118  117800  1920         3          2       2    No        North
118     119  150200  1950         3          2       3   Yes        North
119     120  109700  1920         2          2       4    No        North
120     1

In [2]:
#Defining Dependent and Independent varaibles for Multinomial Logistic Regression
import statsmodels.api as st
X = housePrices[["Price","SqFt","Brick"]]
X['Brick'] = X['Brick'].factorize()[0]
X = st.add_constant(X, prepend=False)
y = housePrices["Neighborhood"]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [3]:
#Fitting Multinomial Logistic Regression
model = st.MNLogit(y, X)
fit = model.fit()
print(fit.summary())

Optimization terminated successfully.
         Current function value: 0.589430
         Iterations 9
                          MNLogit Regression Results                          
Dep. Variable:           Neighborhood   No. Observations:                  128
Model:                        MNLogit   Df Residuals:                      120
Method:                           MLE   Df Model:                            6
Date:                Wed, 14 Jun 2017   Pseudo R-squ.:                  0.4625
Time:                        12:38:57   Log-Likelihood:                -75.447
converged:                       True   LL-Null:                       -140.38
                                        LLR p-value:                 1.376e-25
Neighborhood=North       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Price              -4.511e-05   2.04e-05     -2.214      0.027    -8.5e-05   -5.18e-06
SqFt 

In [4]:
#predicting probabilities for the above multinomial logistic regression
predictedProbab = fit.predict(X)
predictedProbab

0         1         2
0    0.394661  0.568912  0.036427
1    0.428160  0.564835  0.007005
2    0.387126  0.556299  0.056574
3    0.235733  0.764169  0.000098
4    0.497205  0.490097  0.012697
5    0.394768  0.563601  0.041630
6    0.308423  0.042354  0.649224
7    0.074060  0.017902  0.908037
8    0.488603  0.498688  0.012710
9    0.297179  0.697819  0.005002
10   0.763056  0.229491  0.007453
11   0.668659  0.328477  0.002865
12   0.299770  0.699182  0.001048
13   0.724190  0.274975  0.000835
14   0.007850  0.000495  0.991656
15   0.014694  0.005135  0.980170
16   0.826311  0.120879  0.052810
17   0.158033  0.841960  0.000006
18   0.529979  0.469328  0.000693
19   0.034542  0.002266  0.963192
20   0.406534  0.537892  0.055574
21   0.420589  0.571568  0.007844
22   0.193969  0.805690  0.000341
23   0.482225  0.517686  0.000090
24   0.678232  0.064717  0.257051
25   0.204867  0.050154  0.744978
26   0.267798  0.127793  0.604409
27   0.253512  0.744488  0.002000
28   0.077384  0.922613  0.000002
29   0.001143  0.000028  0.998829
..        ...       ...       ...
98   0.101531  0.032260  0.866210
99   0.048495  0.002519  0.948986
100  0.313911  0.685480  0.000609
101  0.547172  0.441878  0.010950
102  0.654704  0.268866  0.076430
103  0.000163  0.000001  0.999836
104  0.146461  0.853532  0.000008
105  0.606363  0.150703  0.242934
106  0.378282  0.620783  0.000934
107  0.750256  0.222657  0.027086
108  0.619135  0.380539  0.000326
109  0.378506  0.620370  0.001124
110  0.360623  0.605700  0.033677
111  0.387639  0.554529  0.057832
112  0.681080  0.316914  0.002006
113  0.606207  0.393565  0.000227
114  0.501496  0.418956  0.079548
115  0.297997  0.700907  0.001096
116  0.000630  0.000008  0.999362
117  0.445279  0.521155  0.033566
118  0.552481  0.077136  0.370384
119  0.370266  0.624503  0.005231
120  0.378346  0.615901  0.005753
121  0.330353  0.667785  0.001862
122  0.786803  0.134292  0.078906
123  0.638877  0.360006  0.001117
124  0.808980  0.115486  0.075534
125  0.425314  0.570158  0.004528
126  0.033973  0.008990  0.957037
127  0.559607  0.423995  0.016397

[128 rows x 3 columns]

In [51]:
#predicting class for the above multinomial logistic regression
predictedClass = [0]*len(predictedProbab)
for i in predictedProbab.index.values:
    predictedClass[i] = np.argmax(np.max(predictedProbab.iloc[[i]]))
predictedClass

[1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 1,
 0,
 2,
 2,
 0,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 2,
 2,
 1,
 0,
 2,
 1,
 0,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 2,
 2,
 1,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 2,
 0]

In [78]:
#Train Test Split
np.random.seed(12345)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [79]:
#Fitting the model on training set
model = st.MNLogit(y_train, X_train)
fit = model.fit()
print(fit.summary())

Optimization terminated successfully.
         Current function value: 0.368962
         Iterations 12
                          MNLogit Regression Results                          
Dep. Variable:           Neighborhood   No. Observations:                   64
Model:                        MNLogit   Df Residuals:                       56
Method:                           MLE   Df Model:                            6
Date:                Mon, 12 Jun 2017   Pseudo R-squ.:                  0.6641
Time:                        08:44:04   Log-Likelihood:                -23.614
converged:                       True   LL-Null:                       -70.296
                                        LLR p-value:                 6.055e-18
Neighborhood=North       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Price              -5.424e-05   4.17e-05     -1.301      0.193      -0.000    2.75e-05
SqFt

In [80]:
#Predicting of test dataset
predictedProbab = fit.predict(X_test)
predictedProbab

0             1             2
121  1.876805e-01  8.123195e-01  1.149977e-09
93   5.682585e-09  8.983810e-10  1.000000e+00
99   9.296740e-06  1.160765e-07  9.999906e-01
94   1.061160e-01  1.830531e-03  8.920535e-01
97   8.468770e-01  1.531230e-01  2.841031e-10
4    4.983353e-01  5.016586e-01  6.074320e-06
70   2.659489e-05  6.558378e-07  9.999727e-01
68   1.988640e-01  8.011360e-01  2.174624e-15
109  3.368032e-01  6.631968e-01  9.326816e-10
24   8.913594e-01  1.570796e-02  9.293265e-02
19   1.045406e-05  2.781891e-07  9.999893e-01
47   1.321449e-01  8.678551e-01  5.410764e-16
25   1.161844e-04  1.361329e-05  9.998702e-01
45   1.183356e-01  8.816644e-01  9.467106e-10
108  7.584713e-01  2.415287e-01  1.345506e-13
16   9.695919e-01  3.031321e-02  9.490268e-05
90   1.982654e-05  1.161690e-05  9.999686e-01
127  6.607304e-01  3.392287e-01  4.090335e-05
33   9.666951e-01  3.330488e-02  5.075069e-08
13   9.001938e-01  9.980616e-02  1.371036e-11
49   4.087929e-01  5.912071e-01  7.477532e-15
39   1.215367e-01  8.784631e-01  1.763136e-07
100  2.108122e-01  7.891878e-01  4.619839e-11
40   6.391377e-02  9.360856e-01  6.692362e-07
48   3.242327e-01  6.757646e-01  2.713478e-06
83   3.537401e-03  2.991230e-04  9.961635e-01
9    9.619884e-02  9.038012e-01  6.096539e-09
84   2.424172e-02  9.757583e-01  1.605165e-12
42   2.212017e-01  7.787983e-01  4.606244e-10
28   1.014430e-02  9.898557e-01  7.522838e-21
..            ...           ...           ...
69   6.994334e-12  6.973029e-13  1.000000e+00
76   2.990391e-01  3.482909e-01  3.526700e-01
71   1.615584e-08  1.887574e-09  1.000000e+00
20   2.022920e-01  7.976426e-01  6.540325e-05
89   1.661794e-01  8.338206e-01  5.160949e-13
51   7.638080e-02  9.236192e-01  1.791876e-14
118  8.734897e-01  5.271766e-02  7.379266e-02
63   3.260100e-01  6.736291e-01  3.609485e-04
111  1.659532e-01  8.339995e-01  4.733372e-05
54   2.304896e-02  9.769510e-01  1.043846e-16
8    4.730193e-01  5.269755e-01  5.148662e-06
37   7.322160e-03  6.213693e-04  9.920565e-01
67   1.667955e-07  4.012168e-08  9.999998e-01
2    1.652044e-01  8.347521e-01  4.354855e-05
6    3.039797e-01  2.569829e-02  6.703220e-01
60   3.503721e-16  1.007933e-17  1.000000e+00
92   8.957076e-04  2.804338e-04  9.988239e-01
32   9.532660e-01  4.673399e-02  2.285636e-09
35   4.194166e-01  5.805819e-01  1.495977e-06
30   3.394118e-08  1.299987e-10  1.000000e+00
103  1.044628e-16  4.269080e-20  1.000000e+00
65   2.623104e-01  7.376896e-01  7.352239e-12
78   5.186602e-01  4.813192e-01  2.062305e-05
44   2.601033e-05  6.711208e-07  9.999733e-01
26   1.007565e-02  6.241034e-03  9.836833e-01
0    1.861797e-01  8.138068e-01  1.346254e-05
112  7.908837e-01  2.091163e-01  6.266506e-11
17   7.929016e-02  9.207098e-01  4.858831e-18
104  5.744061e-02  9.425594e-01  5.326620e-18
21   3.144341e-01  6.855655e-01  3.508088e-07

[64 rows x 3 columns]

In [81]:
#predicting class of test dataset observations
predictedClass1 = [0]*len(predictedProbab)
for i in range(0,len(predictedProbab)):
    predictedClass1[i] = np.argmax(np.max(predictedProbab.iloc[[i]]))
predictedClass1

[1,
 2,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 1]

In [82]:
#Confusion Matrix for test data
CM = pd.crosstab(np.asarray(y_test), np.asarray(predictedClass1),rownames=['Actual'],colnames=['Predicted'])
CM

Predicted  0   1   2
Actual              
East       7  14   3
North      5  17   1
West       0   0  17

In [93]:
#calculating the accuracy for above confusion matrix
acc = (CM[0][0] + CM[1][1] + CM[2][2])/np.sum(np.sum(CM))
acc

0.640625

In [389]:
#Generating Majority Voters Data
Vote1 = [randint(0,1) for i in range(20)]
Vote2 = [randint(0,1) for i in range(20)]
Vote3 = [randint(0,1) for i in range(20)]

In [392]:
#creating dependent variable for the generated data
booleanMajority = [0]*len(Vote1)
for i in range(len(Vote1)):
    if((Vote1[i]+Vote2[i]+Vote3[i])>=2):
        booleanMajority[i] = 1
    else:
        booleanMajority[i] = 0
votersMajority = pd.DataFrame(data={'Vote1': Vote1, "Vote2":Vote2, "Vote3":Vote3, "booleanMajority":booleanMajority})

In [393]:
#train test split of votersMajority data
np.random.seed(123457)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(votersMajority[["Vote1","Vote2","Vote3"]],votersMajority[["booleanMajority"]], test_size=0.5)

In [394]:
#fitting logistic regression on training data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
fit = model.fit(X_train, y_train.ix[:,0])

In [395]:
#coefficient value for the intercept (X0)
fit.intercept_

array([-0.77376178])

In [396]:
#coefficients for the three variables
fit.coef_

array([[ 0.44771231,  0.41878371,  0.47678905]])

In [397]:
#Predicting train and test data using fitted model
predictedTrain = fit.predict(X_train)
predictedTest = fit.predict(X_test)

In [398]:
#Confusion Matrix for train and test data
CMTrain = pd.crosstab(np.asarray(y_train.ix[:,0]),np.asarray(predictedTrain), rownames=['Actual'], colnames=['Predicted'])
CMTest = pd.crosstab(np.asarray(y_test.ix[:,0]),np.asarray(predictedTest), rownames=["Actual"], colnames=["Predicted"])

In [399]:
#confusion matrix for the training data
CMTrain

Predicted  0  1
Actual         
0          6  0
1          0  4

In [400]:
#confusion matrix for the test data
CMTest

Predicted  0  1
Actual         
0          4  0
1          0  6

In [2]:
#Generating XOR data randomly
import numpy as np
np.random.seed(123457)
X1 = [np.random.randint(0,2) for i in range(147)]
X2 = [np.random.randint(0,2) for i in range(147)]

In [4]:
#assigning dependent variable value based on the generated data
import pandas as pd
y = [0]*len(X1)
for i in range(len(X1)):
    if (X1[i] == X2[i]):
        y[i] = 0
    else:
        y[i] = 1
XORdata = pd.DataFrame(data={'X1': X1, "X2":X2, "y":y})

In [5]:
#Running Logistic Regression on XOR data
import statsmodels.api as sm
import statsmodels.formula.api as smf
glmLog = smf.glm(formula = 'y ~ X1+X2', data=XORdata, family = sm.families.Binomial(sm.families.links.logit)).fit()
print(glmLog.summary())

                 Generalized Linear Model Regression Results                  
Dep. Variable:                      y   No. Observations:                  147
Model:                            GLM   Df Residuals:                      144
Model Family:                Binomial   Df Model:                            2
Link Function:                  logit   Scale:                             1.0
Method:                          IRLS   Log-Likelihood:                -100.50
Date:                Mon, 26 Jun 2017   Deviance:                       201.01
Time:                        14:36:31   Pearson chi2:                     148.
No. Iterations:                     4                                         
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4944      0.315      1.569      0.117      -0.123       1.112
X1            -0.3904      0.335     -1.165      0.2

In [6]:
#Prediction on training data using fitted model
#Generating Predictions as probabilities
predictedProbability = glmLog.predict(XORdata[["X1","X2"]])
#Defining Cutoff
cutoff = 0.5
#Generating Prediction Class
import numpy as np
predicted = np.where(predictedProbability > 0.5, 1, 0)
predicted

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1])

In [7]:
#Confusion Matrix for above logistic model
CM = pd.crosstab(np.asarray(XORdata.ix[:,"y"]),np.asarray(predicted), rownames=['Actual'], colnames=['Predicted'])
CM

Predicted   0   1
Actual           
0          38  29
1           0  80

In [45]:
#Neural Network
from sklearn.neural_network import MLPClassifier
X = XORdata[["X1","X2"]]
y = XORdata["y"]
clf = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(2,))
clf.fit(X,y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(2,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [46]:
#The ith element in the list represents the weight matrix corresponding to layer i.
clf.coefs_

[array([[ 6.49052212, -5.90370278],
        [-6.48892247,  7.83112607]]), array([[ 3.36740026],
        [ 5.41839051]])]

In [47]:
#The ith element in the list represents the bias vector corresponding to layer i + 1
clf.intercepts_

[array([-0.11938876, -2.93360768]), array([-9.22398722])]

In [48]:
#predicting XOR data using the fitted neural network model
predicted = clf.predict(X)
predicted

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

In [49]:
#creating a confusion matrix for neural network model
CM = pd.crosstab(np.asarray(y),np.asarray(predicted), rownames=['Actual'], colnames=['Predicted'])
CM

Predicted   0   1
Actual           
0          67   0
1           0  80

In [59]:
#Iris data neural networks
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets

iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [60]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4)

In [61]:
X_train.shape, y_train.shape

((90, 4), (90,))

In [62]:
X_test.shape, y_test.shape

((60, 4), (60,))

In [63]:
#Initializing and fitting neural net on iris data
clf = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(3,))
clf.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(3,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [64]:
#The ith element in the list represents the weight matrix corresponding to layer i.
clf.coefs_

[array([[ 1.67932085, -0.79990698, -0.69589842],
        [ 4.70302132, -1.67302494,  0.34297993],
        [-6.07960426,  2.18395636,  0.62195318],
        [-2.84734206,  4.35448604, -0.38367558]]),
 array([[ 7.51516003, -1.67673104, -6.13900643],
        [-1.72107685, -0.45521444,  3.30615907],
        [ 0.92009918, -0.57222818,  0.87054152]])]

In [65]:
#The ith element in the list represents the bias vector corresponding to layer i + 1
clf.intercepts_

[array([ 0.54866591, -2.84869033,  0.69126445]),
 array([ -4.03278315,  12.34059753,  -8.37237661])]

In [66]:
#making predictions on the test data using the fitted model
predicted = clf.predict_proba(X_test)
j = 0
predictedClass = [0]*len(predicted)
for i in predicted.tolist():
    predictedClass[j] = i.index((max(i)))
    j = j+1
    
predictedClass

[0,
 2,
 1,
 0,
 2,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 1,
 1,
 0,
 2,
 0,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 2,
 0,
 2,
 2,
 0,
 0,
 1,
 1,
 1,
 2,
 0]

In [67]:
#creating a confusion matrix for neural network model
CM = pd.crosstab(np.asarray(y_test),np.asarray(predictedClass), rownames=['Actual'], colnames=['Predicted'])
CM

Predicted   0   1   2
Actual               
0          26   0   0
1           0  23   0
2           0   0  11